spring:
  datasource:
    url: jdbc:h2:mem:dt2025  # Banco H2 em memória com nome dt2025
    username: dt2025
    password: 
    driver-class-name: org.h2.Driver  # Driver do banco H2

  jpa:
    show-sql: true  # Exibe as queries executadas
    open-in-view: false
    hibernate:
      ddl-auto: create  # Pode ser 'validate', 'update', 'create-drop'
    properties:
      hibernate:
        format_sql: true  # Formatação das queries SQL

  h2:
    console:
      enabled: true
      path: /h2-console  # Caminho para acessar o console H2 no browser
      settings:
        trace: false
        web-allow-others: false  # Impede o acesso ao console por outros dispositivos

